/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cyhal.h"
#include "cybsp.h"
#include "cy_retarget_io.h"
#include "cy_tcpwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* A flag when true indicating that the user process has finished within the time limit */
bool g_taskDone;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* TCPWM interrupt configuration structure 0 */
const cy_stc_sysint_t IRQ_CFG_0 =
{
    .intrSrc = ((NvicMux4_IRQn << 16) | tcpwm_0_interrupts_0_IRQn),
    .intrPriority = 3UL
};

/* TCPWM interrupt configuration structure 1 */
const cy_stc_sysint_t IRQ_CFG_1 =
{
    .intrSrc = ((NvicMux5_IRQn << 16) | tcpwm_0_interrupts_1_IRQn),
    .intrPriority = 0UL
};

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: start_TCPWM_Counter
 * Summary:
 *  This function starts timer after setting counter value to zero.
 * Parameters:
 *  none
 * Retrun:
 *  none
 **********************************************************************************************************************
 */
static void start_TCPWM_Counter(TCPWM_Type *base, uint32_t cntNum)
{
    Cy_TCPWM_Counter_SetCounter(base, cntNum, 0);
    Cy_TCPWM_TriggerStart_Single(base, cntNum);
}

/**********************************************************************************************************************
 * Function Name: handle_TCPWM_Counter_Interrupt
 * Summary:
 *  This is the handler function for counter interrupt.
 * Parameters:
 *  none
 * Retrun:
 *  none
 **********************************************************************************************************************
 */
static void handle_TCPWM_Counter_Interrupt(void)
{
    if (Cy_TCPWM_GetInterruptStatusMasked(COUNTER_1S_HW, COUNTER_1S_NUM) != 0)
    {
        /* Start TCPWM for Timing Protection NMI */
        start_TCPWM_Counter(COUNTER_2S_HW, COUNTER_2S_NUM);

        /* Clear TCPWM CC0 interrupt flag */
        Cy_TCPWM_ClearInterrupt(COUNTER_1S_HW, COUNTER_1S_NUM, CY_TCPWM_INT_ON_CC0);

        /* user program here.. */
        {
            ;
        }

        /* Indicates that a task has been started whose duration should be monitored */
        cyhal_gpio_write(CYBSP_USER_LED1, CYBSP_LED_STATE_ON);

        printf("Press USER_BTN1 within 2 seconds...\r\n");

        /* Waiting until user button pushed */
        while (1)
        {
            if (cyhal_gpio_read(CYBSP_USER_BTN) == CYBSP_BTN_PRESSED)
            {
                /* Stop TCPWM for Timing Protection NMI */
                Cy_TCPWM_TriggerStopOrKill_Single(COUNTER_2S_HW, COUNTER_2S_NUM);

                /* Indicates that the task finished its process */
                cyhal_gpio_write(CYBSP_USER_LED1, CYBSP_LED_STATE_OFF);
                printf("Pressed within time limit!\r\n\n");
                g_taskDone = true;
                break;
            }
        }
    }
}

/**********************************************************************************************************************
 * Function Name: NMIException_Handler
 * Summary:
 *  This is the handler function for NMI interrupt.
 *  This function overrides Default_NMIException_Handler, directly registered to __Vectors.
 * Parameters:
 *  none
 * Retrun:
 *  none
 **********************************************************************************************************************
 */
void NMIException_Handler(void)
{
    if (Cy_TCPWM_GetInterruptStatusMasked(COUNTER_2S_HW, COUNTER_2S_NUM) != 0)
    {
        /* Clear TCPWM CC0 interrupt flag */
        Cy_TCPWM_ClearInterrupt(COUNTER_2S_HW, COUNTER_2S_NUM, CY_TCPWM_INT_ON_CC0);

        /* Indicates that processing time exceeds limit */
        cyhal_gpio_write(CYBSP_USER_LED2, CYBSP_LED_STATE_ON);
        printf("2 seconds exceeded, process terminated...\r\n");

        while (1)
        {
            ;
        }
    }
}

/**********************************************************************************************************************
 * Function Name: init_Timer
 * Summary:
 *  This function configures a 2 TCPWMs as One-shot counter.
 *  The handler of one is set as IRQ, another is set as NMI.
 * Parameters:
 *  none
 * Retrun:
 *  none
 **********************************************************************************************************************
 */
static void init_Timer(void)
{
    /* Initialize TCPWM0_GRPx_CNTx_COUNTER 0 as Counter */
    CY_ASSERT(Cy_TCPWM_Counter_Init(COUNTER_1S_HW, COUNTER_1S_NUM, &COUNTER_1S_config) == CY_TCPWM_SUCCESS);
    /* Initialize TCPWM0_GRPx_CNTx_COUNTER 1 as Counter */
    CY_ASSERT(Cy_TCPWM_Counter_Init(COUNTER_2S_HW, COUNTER_2S_NUM, &COUNTER_2S_config) == CY_TCPWM_SUCCESS);
    /* Enable TCPWM0_GRPx_CNTx_COUNTER 0 */
    Cy_TCPWM_Counter_Enable(COUNTER_1S_HW, COUNTER_1S_NUM);
    /* Enable TCPWM0_GRPx_CNTx_COUNTER 1 */
    Cy_TCPWM_Counter_Enable(COUNTER_2S_HW, COUNTER_2S_NUM);

    /* Enable Interrupt for both the counters */
    Cy_TCPWM_SetInterruptMask(COUNTER_1S_HW, COUNTER_1S_NUM, CY_TCPWM_INT_ON_CC0);
    Cy_TCPWM_SetInterruptMask(COUNTER_2S_HW, COUNTER_2S_NUM, CY_TCPWM_INT_ON_CC0);

    /* Set NMI mapping */
    Cy_SysInt_SetNmiSource(CY_SYSINT_NMI1, tcpwm_0_interrupts_1_IRQn);

    /*  Interrupt setting for TCPWMs  */
    CY_ASSERT(Cy_SysInt_Init(&IRQ_CFG_0, handle_TCPWM_Counter_Interrupt) == CY_SYSINT_SUCCESS);
    CY_ASSERT(Cy_SysInt_Init(&IRQ_CFG_1, NMIException_Handler) == CY_SYSINT_SUCCESS);

    /* Enable the Interrupt */
    NVIC_EnableIRQ(NvicMux4_IRQn);
}

/**********************************************************************************************************************
 * Function Name: main
 * Summary:
 *  This is the main function.
 * Parameters:
 *  none
 * Retrun:
 *  int
 **********************************************************************************************************************
 */
int main(void)
{
#if defined (CY_DEVICE_SECURE)
    cyhal_wdt_t wdtObj;

    /* Clear watchdog timer so that it doesn't trigger a reset */
    CY_ASSERT(cyhal_wdt_init(&wdtObj, cyhal_wdt_get_max_timeout_ms()) == CY_RSLT_SUCCESS);
    cyhal_wdt_free(&wdtObj);
#endif /* #if defined (CY_DEVICE_SECURE) */

    /* Initialize the device and board peripherals */
    CY_ASSERT(cybsp_init() == CY_RSLT_SUCCESS);

    /* Enable global interrupts */
    __enable_irq();

    /* Initialize retarget-io to use the debug UART port */
    CY_ASSERT(cy_retarget_io_init(CYBSP_DEBUG_UART_TX, CYBSP_DEBUG_UART_RX,
                                  CY_RETARGET_IO_BAUDRATE) == CY_RSLT_SUCCESS);

    /* Initialize the User LED */
    CY_ASSERT(cyhal_gpio_init(CYBSP_USER_LED1, CYHAL_GPIO_DIR_OUTPUT,
                              CYHAL_GPIO_DRIVE_STRONG, CYBSP_LED_STATE_OFF) == CY_RSLT_SUCCESS);
    CY_ASSERT(cyhal_gpio_init(CYBSP_USER_LED2, CYHAL_GPIO_DIR_OUTPUT,
                              CYHAL_GPIO_DRIVE_STRONG, CYBSP_LED_STATE_OFF) == CY_RSLT_SUCCESS);

    /* Initialize the User Button */
    CY_ASSERT(cyhal_gpio_init(CYBSP_USER_BTN, CYHAL_GPIO_DIR_INPUT,
                              CYHAL_GPIO_DRIVE_PULLUP, CYBSP_BTN_OFF) == CY_RSLT_SUCCESS);

    /* \x1b[2J\x1b[;H - ANSI ESC sequence for clear screen */
    printf("\x1b[2J\x1b[;H");

    printf("****************** "
           "Timing Protection using NMI example "
           "****************** \r\n\n");

    printf("Press USER_BTN1 within 2 seconds after USER_LED1 lights up\r\n"
           "If not pressed, USER_LED2 lights up and the process is terminated\r\n\n");

    /* Initialize TCPWM to generate interrupts */
    init_Timer();

    g_taskDone = true;

    while (1)
    {
        if (g_taskDone)
        {
            g_taskDone = false;

            /* Start timer */
            start_TCPWM_Counter(COUNTER_1S_HW, COUNTER_1S_NUM);
        }
    }
}

/* [] END OF FILE */
